/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import lapr.project.controller.CreateProjectController;
import lapr.project.utils.ImportException;

/**
 *
 * @author MarioDias
 */
public class CreateProjectUI extends JDialog {

    private JFileChooser jfc;

    private transient final CreateProjectController controller;
    boolean validProject;
    private static final long serialVersionUID = 1;
    private static final String IMPORT_NETWORK_TITLE = "Import RoadNetwork";
    private static final String IMPORT_VEHICLE_TITLE = "Import Vehicles";

    /**
     * Creates new form CreateProjectUI
     *
     * @param parent
     */
    public CreateProjectUI(JFrame parent) {
        super(parent, true);
        controller = new CreateProjectController();
        initComponents();
        initFileChooser();
        validProject = false;

    }

    public void initFileChooser() {
        jfc = new JFileChooser();
        FileNameExtensionFilter xmlfilter = new FileNameExtensionFilter("XML files (*.xml)", "xml");
        jfc.setFileFilter(xmlfilter);
        jfc.setCurrentDirectory(new File(System.getProperty("user.dir")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfield_project_title = new javax.swing.JTextField();
        labelTitle = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnCreateProject = new javax.swing.JButton();
        btnImportRoadNetwork = new javax.swing.JButton();
        btnImportVehicle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfld_description = new javax.swing.JTextArea();
        labelTitle1 = new javax.swing.JLabel();
        newRoadNetworkJLabel = new javax.swing.JLabel();
        newVehiclesJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Project");

        txtfield_project_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_project_titleActionPerformed(evt);
            }
        });

        labelTitle.setText("Project title:");

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/return_icon.png"))); // NOI18N
        btnClose.setText("Cancel");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnCreateProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ok_icon.png"))); // NOI18N
        btnCreateProject.setText("Create project");
        btnCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProjectActionPerformed(evt);
            }
        });

        btnImportRoadNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roadNetwork_icon.png"))); // NOI18N
        btnImportRoadNetwork.setText("Import Road Network");
        btnImportRoadNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportRoadNetworkActionPerformed(evt);
            }
        });

        btnImportVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicle_icon.png"))); // NOI18N
        btnImportVehicle.setText("Import Vehicle");
        btnImportVehicle.setToolTipText("");
        btnImportVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportVehicleActionPerformed(evt);
            }
        });

        txtfld_description.setColumns(20);
        txtfld_description.setRows(5);
        jScrollPane1.setViewportView(txtfld_description);

        labelTitle1.setText("Description:");

        newRoadNetworkJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check_icon.png"))); // NOI18N
        newRoadNetworkJLabel.setText("Not Imported");
        newRoadNetworkJLabel.setEnabled(false);

        newVehiclesJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check_icon.png"))); // NOI18N
        newVehiclesJLabel.setText("Not Imported");
        newVehiclesJLabel.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImportVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(btnImportRoadNetwork))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTitle)
                            .addComponent(labelTitle1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(txtfield_project_title))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnClose)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(newVehiclesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newRoadNetworkJLabel)
                                .addComponent(btnCreateProject)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfield_project_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportVehicle)
                    .addComponent(btnImportRoadNetwork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newRoadNetworkJLabel)
                    .addComponent(newVehiclesJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateProject)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();


    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProjectActionPerformed
        String title = txtfield_project_title.getText().trim();
        String description = txtfld_description.getText().trim();
        if (controller.getVehicleList().isEmpty() || controller.getRoadList().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Load Files First", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (controller.getRoadNetwork().numVertices() == 0 || controller.getRoadNetwork().numEdges() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Load Files First", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    if (!controller.createProject(title, description)) {
                        JOptionPane.showMessageDialog(rootPane, "Name and description already exist or are empty.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Project was created successfully", "Created a project", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(CreateProjectUI.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(rootPane, String.format("Error trying to connect to the database.\n Information Error: %s", ex.getMessage()));
                }
            }
        }
    }//GEN-LAST:event_btnCreateProjectActionPerformed

    private void btnImportVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportVehicleActionPerformed
        jfc.setDialogTitle(IMPORT_VEHICLE_TITLE);
        int returnvalue = jfc.showOpenDialog(this);
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            try {
                controller.importVehicle(jfc.getSelectedFile());
                newVehiclesJLabel.setEnabled(true);
                newVehiclesJLabel.setText("Imported");
                JOptionPane.showMessageDialog(this, "Vehicles were imported with success.", "Vehicle import", JOptionPane.INFORMATION_MESSAGE);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "There was an error importing the file", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ImportException ex) {
                JOptionPane.showMessageDialog(this, "There was an error importing the file", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnImportVehicleActionPerformed

    private void btnImportRoadNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportRoadNetworkActionPerformed
        jfc.setDialogTitle(IMPORT_NETWORK_TITLE);
        int returnvalue = jfc.showOpenDialog(this);
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            try {
                controller.importNetwork(jfc.getSelectedFile());
                newRoadNetworkJLabel.setEnabled(true);
                newRoadNetworkJLabel.setText("Imported");
                JOptionPane.showMessageDialog(this, "Roadnetwork was imported with success.", "Roadnetwork import", JOptionPane.INFORMATION_MESSAGE);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "There was an error importing the file", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ImportException ex) {
                JOptionPane.showMessageDialog(this, "There was an error importing the file", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnImportRoadNetworkActionPerformed

    private void txtfield_project_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_project_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_project_titleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreateProject;
    private javax.swing.JButton btnImportRoadNetwork;
    private javax.swing.JButton btnImportVehicle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JLabel newRoadNetworkJLabel;
    private javax.swing.JLabel newVehiclesJLabel;
    private javax.swing.JTextField txtfield_project_title;
    private javax.swing.JTextArea txtfld_description;
    // End of variables declaration//GEN-END:variables
}
