/*
 */
package lapr.project.ui;

import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import lapr.project.controller.EditProjectController;
import lapr.project.model.Vehicle;
import lapr.project.utils.ImportException;

/**
 *
 * @author pc asus
 */
public class EditProjectUI extends javax.swing.JDialog {

    private static final long serialVersionUID = 1;
    private EditProjectController controller;
    private JFileChooser jfc;
    private static final String IMPORT_NETWORK_TITLE = "Import RoadNetwork";
    private static final String IMPORT_VEHICLE_TITLE = "Import Vehicles";

    /**
     * Creates new form EditProjectUI
     */
    public EditProjectUI(JFrame parent) {
        super(parent, true);
        initComponents();
        initFileChooser();
        controller = new EditProjectController();
        if (controller.getActiveProject() == null) {
            JOptionPane.showMessageDialog(this, "There is not an active project at the moment.\nPress OK to close");
        } else {
            jtf_currentProject.setText(controller.getActiveProjectName());
            jtf_name.setText(controller.getActiveProjectName());
            jtf_description.setText(controller.getActiveProjectDescription());
        }
    }

    public void initFileChooser() {
        jfc = new JFileChooser();
        FileNameExtensionFilter xmlfilter = new FileNameExtensionFilter("XML files (*.xml)", "xml");
        jfc.setFileFilter(xmlfilter);
        jfc.setCurrentDirectory(new File(System.getProperty("user.dir")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_name = new javax.swing.JLabel();
        jl_description = new javax.swing.JLabel();
        jtf_name = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jl_name1 = new javax.swing.JLabel();
        jtf_currentProject = new javax.swing.JTextField();
        newRoadNetworkButton = new javax.swing.JButton();
        newVehiclesButton = new javax.swing.JButton();
        newVehiclesJLabel = new javax.swing.JLabel();
        newRoadNetworkJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtf_description = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Project");

        jl_name.setText("Name:");

        jl_description.setText("Description");

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save_icon.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/return_icon.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jl_name1.setText("Current Project:");

        jtf_currentProject.setEditable(false);

        newRoadNetworkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roadNetwork_icon.png"))); // NOI18N
        newRoadNetworkButton.setText("New Roads");
        newRoadNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRoadNetworkButtonActionPerformed(evt);
            }
        });

        newVehiclesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicle_icon.png"))); // NOI18N
        newVehiclesButton.setText("New Vehicles");
        newVehiclesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVehiclesButtonActionPerformed(evt);
            }
        });

        newVehiclesJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check_icon.png"))); // NOI18N
        newVehiclesJLabel.setText("Not Imported");
        newVehiclesJLabel.setEnabled(false);

        newRoadNetworkJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check_icon.png"))); // NOI18N
        newRoadNetworkJLabel.setText("Not Imported");
        newRoadNetworkJLabel.setEnabled(false);

        jtf_description.setColumns(20);
        jtf_description.setRows(5);
        jScrollPane1.setViewportView(jtf_description);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newVehiclesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(newRoadNetworkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newRoadNetworkJLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newVehiclesJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(65, 65, 65))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jl_description)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_name1)
                            .addComponent(jl_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_name, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(jtf_currentProject))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_name1)
                    .addComponent(jtf_currentProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newVehiclesButton)
                    .addComponent(newVehiclesJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newRoadNetworkButton)
                    .addComponent(newRoadNetworkJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String nameProject = jtf_name.getText();
        String descriptionProject = jtf_description.getText();
        boolean nameChanges = true;
        boolean roadUpdate = true;
        boolean vehicleUpdate = true;
        if (nameProject.equals(controller.getActiveProjectName()) && descriptionProject.equals(controller.getActiveProjectDescription())) {
            nameChanges = false;
        }
        if (!newVehiclesJLabel.getText().equalsIgnoreCase("Imported")) {
            vehicleUpdate = false;
        }
        if (!newRoadNetworkJLabel.getText().equalsIgnoreCase("Imported")) {
            roadUpdate = false;
        }
        boolean check = controller.updateProject(nameChanges, nameProject, descriptionProject, vehicleUpdate, roadUpdate);
        if (check) {
            JOptionPane.showMessageDialog(this, "Project edited successfully");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Project was not changed");
            dispose();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void newVehiclesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVehiclesButtonActionPerformed
        jfc.setDialogTitle(IMPORT_VEHICLE_TITLE);
        int returnvalue = jfc.showOpenDialog(this);
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            try {
                controller.addVehicles(jfc.getSelectedFile());
                newVehiclesJLabel.setEnabled(true);
                newVehiclesJLabel.setText("Imported");
                JOptionPane.showMessageDialog(this, "Vehicles were imported with success.", "Vehicle import", JOptionPane.INFORMATION_MESSAGE);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "There was an error importing the file", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ImportException ex) {
                JOptionPane.showMessageDialog(this, "There was an error importing the file", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_newVehiclesButtonActionPerformed

    private void newRoadNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRoadNetworkButtonActionPerformed
        jfc.setDialogTitle(IMPORT_NETWORK_TITLE);
        int returnvalue = jfc.showOpenDialog(this);
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            try {
                controller.addRoadNetwork(jfc.getSelectedFile());
                newRoadNetworkJLabel.setEnabled(true);
                newRoadNetworkJLabel.setText("Imported");
                JOptionPane.showMessageDialog(this, "Roadnetwork was imported with success.", "Roadnetwork import", JOptionPane.INFORMATION_MESSAGE);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "There was an error importing the file", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ImportException ex) {
                JOptionPane.showMessageDialog(this, "There was an error importing the file", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_newRoadNetworkButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_description;
    private javax.swing.JLabel jl_name;
    private javax.swing.JLabel jl_name1;
    private javax.swing.JTextField jtf_currentProject;
    private javax.swing.JTextArea jtf_description;
    private javax.swing.JTextField jtf_name;
    private javax.swing.JButton newRoadNetworkButton;
    private javax.swing.JLabel newRoadNetworkJLabel;
    private javax.swing.JButton newVehiclesButton;
    private javax.swing.JLabel newVehiclesJLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
