/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

/**
 *
 * @author MarioDias
 */
public class Mockup extends javax.swing.JFrame {
    private static final long serialVersionUID = 1;
    /**
     * Creates new form Mockup
     */
    public Mockup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemProject = new javax.swing.JMenu();
        menuItemCreateProject = new javax.swing.JMenuItem();
        menuItemOpenProject = new javax.swing.JMenuItem();
        itemProjectEditProject = new javax.swing.JMenuItem();
        itemProjectCopyProject = new javax.swing.JMenuItem();
        menuNetworkAnalysis = new javax.swing.JMenu();
        menuItemBestPath = new javax.swing.JMenu();
        menuResults = new javax.swing.JMenu();
        menuItemSave = new javax.swing.JMenu();
        menuItemExportShow = new javax.swing.JMenu();
        subMenuItemExport = new javax.swing.JMenu();
        subMenuItemExportCSV = new javax.swing.JMenu();
        subItemMenuShow = new javax.swing.JMenu();
        menuItemFile = new javax.swing.JMenu();
        menuItemSaveFile = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClose.setText("Close");

        itemProject.setText("Project");

        menuItemCreateProject.setText("Create new project");
        itemProject.add(menuItemCreateProject);

        menuItemOpenProject.setText("Open project");
        itemProject.add(menuItemOpenProject);

        itemProjectEditProject.setText("Edit project");
        itemProject.add(itemProjectEditProject);

        itemProjectCopyProject.setText("Copy project");
        itemProject.add(itemProjectCopyProject);

        jMenuBar1.add(itemProject);

        menuNetworkAnalysis.setText("Network Analysis");

        menuItemBestPath.setText("Shortest/Best path");
        menuNetworkAnalysis.add(menuItemBestPath);

        jMenuBar1.add(menuNetworkAnalysis);

        menuResults.setText("Results");

        menuItemSave.setText("Save current results into project");
        menuResults.add(menuItemSave);

        menuItemExportShow.setText("Export/Show");

        subMenuItemExport.setText("Export HTML");
        menuItemExportShow.add(subMenuItemExport);

        subMenuItemExportCSV.setText("Export CSV");
        menuItemExportShow.add(subMenuItemExportCSV);

        subItemMenuShow.setText("Show results");
        menuItemExportShow.add(subItemMenuShow);

        menuResults.add(menuItemExportShow);

        jMenuBar1.add(menuResults);

        menuItemFile.setText("File");

        menuItemSaveFile.setText("Save current project");
        menuItemFile.add(menuItemSaveFile);

        jMenuBar1.add(menuItemFile);

        menuHelp.setText("Help");
        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(504, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mockup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mockup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mockup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mockup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mockup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JMenu itemProject;
    private javax.swing.JMenuItem itemProjectCopyProject;
    private javax.swing.JMenuItem itemProjectEditProject;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuItemBestPath;
    private javax.swing.JMenuItem menuItemCreateProject;
    private javax.swing.JMenu menuItemExportShow;
    private javax.swing.JMenu menuItemFile;
    private javax.swing.JMenuItem menuItemOpenProject;
    private javax.swing.JMenu menuItemSave;
    private javax.swing.JMenuItem menuItemSaveFile;
    private javax.swing.JMenu menuNetworkAnalysis;
    private javax.swing.JMenu menuResults;
    private javax.swing.JMenu subItemMenuShow;
    private javax.swing.JMenu subMenuItemExport;
    private javax.swing.JMenu subMenuItemExportCSV;
    // End of variables declaration//GEN-END:variables
}
